[[block]]
block = "uptime"

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "load"
interval = 5

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%a %d/%m %R') "
interval = 60


[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"


[icons]
icons = "material"

[theme]
theme = "modern"
[theme.overrides]
idle_bg = "#edf5e2"
idle_fg = "#221321"
warning_bg = "#b0b7aa"
warning_fg = "#000000"
separator = ""
critical_bg = "#c3303a"
critical_fg = "#000000"
good_bg = "#e0e0e0"
good_fg = "#000000"
info_bg = "#e0e0e0"
info_fg = "#000000"
