background = "#ffffffff"
blend = true
blocks_overlap = 0.0
blocks_r = 2
color = "#cba6f7ff"
command = "i3status-rs"
font = "Recursive Mono Casual Static 12"
height = 20
hide_inactive_tags = true
invert_touchpad_scrolling = true
margin_bottom = 3
#margin_left = 8
#margin_right = 8
margin_top = 4
position = "top"
#separator = "#9a8a62ff"
separator_width = 0
show_layout_name = false
tag_bg = "#f2f2f2ff"
tag_fg = "#000000ff"
tag_focused_bg = "#c4c4c4ff"
tag_focused_fg = "#000000ff"
tag_inactive_bg = "#e0e0e0ff"
tag_inactive_fg = "#000000ff"
tag_urgent_bg = "#d00000ff"
tag_urgent_fg = "#000000ff"
tags_padding = 15.0
tags_r = 4

[wm.river]
max_tag = 9
